# Generated by Django 4.2.1 on 2023-07-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='trans_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
