# Generated by Django 4.2.1 on 2023-07-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_paymenttransaction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='qr_image',
            field=models.ImageField(null=True, upload_to='qr_code_images'),
        ),
    ]
