# Generated by Django 4.2.1 on 2023-07-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0004_paymenttransaction_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='qr_image',
        ),
    ]
