# Generated by Django 4.2.1 on 2023-08-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0002_reciepts_reciept_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciepts',
            name='reciept_id',
        ),
    ]
