# Generated by Django 4.2.1 on 2023-09-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0003_remove_reciepts_reciept_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciepts',
            old_name='time',
            new_name='created_time',
        ),
    ]
