# Generated by Django 4.2.1 on 2023-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuredFood', models.CharField(max_length=100)),
                ('expectedQuantity', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=50)),
                ('tquantity', models.IntegerField()),
                ('tamount', models.IntegerField()),
            ],
        ),
    ]
