# Generated by Django 4.1.7 on 2023-09-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_dailyrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='tamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='records',
            name='tquantity',
            field=models.IntegerField(default=0),
        ),
    ]
