# Generated by Django 4.2.1 on 2023-07-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_order_qrc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scaned_time',
            field=models.DateTimeField(null=True),
        ),
    ]
