# Generated by Django 4.2.1 on 2023-07-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_order_scaned_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reciept',
            field=models.FileField(null=True, upload_to='reciepts'),
        ),
    ]
