# Generated by Django 4.1.7 on 2023-09-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order_reciept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='scaned_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
