# Generated by Django 4.2.1 on 2023-09-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_order_scaned_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('MPESA', 'mpesa'), ('QCOINS', 'qcoins')], default='mpesa', max_length=50),
        ),
    ]
