# Generated by Django 5.0.3 on 2024-03-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='scaned_time',
            field=models.DateTimeField(null=True),
        ),
    ]
